### ISSUE TITLE
Not working with Minecraft 1.21

### ISSUE THREAD

**Issue by marcopiraccini** [gilesknap/mciwb#141]
Opening a shell for a player I get:
```
mcipc.rcon.exceptions.UnexpectedTrailingData: ...t:oak_sign{BlockEntityTag:{front_text:{messages:['["select"]','[""]','[""]','[""]']}},display:{Name:'{"text":"select"}'}}
```

On the `give` command

Debugging, the exact error is:

```
Expected whitespace to end one argument, but found trailing data...t:oak_sign{BlockEntityTag:{front_text:{messages:['["select"]','[""]','[""]','[""]']}},display:{Name:'{"text":"select"}'}}<--[HERE]
````

**Comment by gilesknap** [comment]
I imagine that the entity tag format has changed or is being more strictly checked.

You ask at a good time because my Son is playing minecraft again and I have a 1.21 server to test against.

Will look a this over the weekend.

Thanks for the report.

**Comment by gilesknap** [comment]
um maybe next weekend. 🙃

**Comment by gilesknap** [comment]
I've reproduced this error but I'm a little stumped as to what is happening. I can't see any documentation relating to changes in the JSON describing signs. I've tried rolling back the version of RCON just to verify that is not where the problem lies.

Still investigating ...

**Comment by gilesknap** [comment]
OK, got it.
This page https://www.gamergeeks.net/apps/minecraft/give-command-generator/signs
shows this for 1.20:
`/give @a oak_sign{BlockEntityTag:{front_text:{messages:['["hello there"]','[""]','[""]','[""]']}}}`
and this for 1.21:
`/give @a oak_sign[block_entity_data={id:oak_sign,front_text:{messages:['["hello there"]','[""]','[""]','[""]']}}]`
