### ISSUE TITLE
Need to enable the windows subsystem for linux optional component for ubuntu WSL

### ISSUE THREAD

**Issue by GarethProdger** [gilesknap/mciwb#60]
![image](https://user-images.githubusercontent.com/89082664/189523077-c8900322-7410-44b6-bf57-b9710df82ba4.png)

**Comment by GarethProdger** [comment]
https://docs.microsoft.com/en-gb/windows/wsl/install

run wsl --install using powershell running as admin

**Comment by gilesknap** [comment]
I think you are saying that you need to do the above before getting ubuntu from the Microsoft store?

Thanks!

**Comment by GarethProdger** [comment]
yes sort of. running the command above tries to install a previous version of ubuntu, but seams to set all the prerequisites which i think is just windows subsystem for linux in windows features. alternatively i could of ticked this setting and installed the latest version of ubunto. hopefully the older version should do the job.

**Comment by gilesknap** [comment]
you do need the latest version of ubuntu because of the python3.10 dependency of one of the libraries I use.

I think you can do the upgrade from the command line. 

I'm not clear about the best sequence to go through to ensure you get WSL2 latest + ubuntu 22.04 but I need to work that out and document it.

**Comment by gilesknap** [comment]
```bash
wsl --set-version Ubuntu-22.04 2
```
Maybe the above will do it for you (from an Admin prompt)

See ``Upgrade version from WSL 1 to WSL 2`` in https://docs.microsoft.com/en-gb/windows/wsl/install

**Comment by GarethProdger** [comment]
thanks giles. I'll give this a go.

**Comment by GarethProdger** [comment]
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The distribution is already the requested version.

**Comment by GarethProdger** [comment]
ah i think that i'm ok

**Comment by GarethProdger** [comment]
I used python3.10 rather than python3.9. have now successfully installed mciwb. 

I'll look at the next tutorial tomorrow

**Comment by gilesknap** [comment]
@GarethProdger 

Do you reckon the correct instructions for WSL and Ubuntu are simply:

```
Open a admin terminal and type:
wsl --set-version Ubuntu-22.04 2
```
