### ISSUE TITLE
Having trouble installing Docker Desktop

### ISSUE THREAD

**Issue by GarethProdger** [gilesknap/mciwb#61]
![image](https://user-images.githubusercontent.com/89082664/189524151-3ff7727d-d0ea-4be6-a084-9568aaa2b61f.png)

have very little space on my c drive, but have over 150GB on my d drive

**Comment by GarethProdger** [comment]
seems you cannot change the install location for the current version of docker but there is a solution here https://forums.docker.com/t/docker-installation-directory/32773 were you create a junction link

**Comment by gilesknap** [comment]
@GarethProdger did you manage to get Docker Desktop working?

I'll be spending more time on this project again as we have a couple more people interested. Let me know if you would like me to drop by and get everything set up for you.

**Comment by gilesknap** [comment]
BTW - re space on your drive. I bet you have your Steam library taking up space?

Try Steam->Settings->Downloads->STEAM LIBRARY FOLDERS 

Hit the + tp create a folder on your big drive and then select games and move them over to the new folder.

**Comment by gilesknap** [comment]
Verbally discussed
