### ISSUE TITLE
Question about Backup and Restore

### ISSUE THREAD

**Issue by compX44** [gilesknap/mciwb#86]
Hello @gilesknap 

I am following along with the Backup and Restore instructions and I have a question. For the part after (.venv), are we using the username info before the @ sign? I tried a variety of ways, but I keep getting a syntax error.

1. useradd@DESKTOP-KSM4GML:~/my_world$ (.venv) [useradd@ws1 mciwb]$ ls $HOME/mciwb-backups
bash: syntax error near unexpected token `[useradd@ws1'

2. useradd@DESKTOP-KSM4GML:~/my_world$ (.venv) [ahUn1t$@ws1 mciwb]$ mciwb restore my-first-backup
bash: syntax error near unexpected token `[ahUn1t$@ws1'

3.  useradd@DESKTOP-KSM4GML:~/my_world$ (.venv) [useradd@DESKTOP-KSM4GML mciwb]$ ls $HOME/mciwb-bqckups
bash: syntax error near unexpected token `[useradd@DESKTOP-KSM4GML'

**Comment by gilesknap** [comment]
Sorry for the confusion.
In my command examples `(.venv) [giles@ws1 mciwb]$ ` is what my prompt looks like. 
So you only need to type the commands after that i.e.
```bash
ls $HOME/mciwb-backups
mciwb restore my-first-backup
```

**Comment by gilesknap** [comment]
I need to tidy up those examples and remove the confusing prompt

**Comment by compX44** [comment]
Ah, okay. I typed the commands and was able to execute them properly. Thanks for your help.

**Comment by gilesknap** [comment]
👍 
I'll leave this open until I have fixed the docs.

**Comment by gilesknap** [comment]
@compX44 
I've tidied up the documentation here https://gilesknap.github.io/mciwb/main/user/how-to/backup.html#backups-of-mciwb-server

**Comment by compX44** [comment]
I just checked out the revisions. Very nice.
